packageExtensions:
  "@microsoft/gulp-core-build-typescript@*":
    dependencies:
      "@microsoft/rush-stack-compiler-3.2": "*"
  "gulp-eslint7@*":
    dependencies:
      "@eslint/eslintrc": "*"
  "@typescript-eslint/eslint-plugin@*":
    dependencies:
      "typescript": "*"
  "@typescript-eslint/typescript-estree@*":
    dependencies:
      "typescript": "*"
  "@typescript-eslint/parser@*":
    dependencies:
      "typescript": "*"
